backend:
  name: github
  repo: Mostafa-Mansour14/mostafa-mansour14.github.io
  branch: main

media_folder: "assets/uploads"
public_folder: "/assets/uploads"

collections:
  - name: "portfolio"
    label: "Portfolio"
    files:
      - file: "data/portfolio.json"
        label: "Videos"
        name: "videos"
        fields:
          - label: "Edit Videos"
            name: "edit"
            widget: "list"
            fields:
              - { label: "Title", name: "title", widget: "string" }
              - { label: "YouTube ID", name: "video", widget: "string" }
              - { label: "Tags", name: "tags", widget: "list", default: [] }

          - label: "Create Videos"
            name: "create"
            widget: "list"
            fields:
              - { label: "Title", name: "title", widget: "string" }
              - { label: "YouTube ID", name: "video", widget: "string" }
              - { label: "Tags", name: "tags", widget: "list", default: [] }
